# Copyright (c) 2016 Kazumasa Kohtaka. All rights reserved.
# This file is available under the MIT license.

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongod-conf
  namespace: mongo-replica-set
data:
  mongod.conf: |
    # Copyright (c) 2016 Kazumasa Kohtaka. All rights reserved.
    # This file is available under the MIT license.

    storage:
        engine: wiredTiger
        dbPath: /mnt/data/
        journal:
            enabled: true

    systemLog:
        verbosity: 1
        timeStampFormat: iso8601-utc

    net:
        port: 27017
        bindIp: 127.0.0.1

    replication:
        oplogSizeMB: 32
        replSetName: graylog
